In [1]:
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
from openai import OpenAI

client = OpenAI()

prompt = """You are an email classification system.
 Classify the following email into one of these categories: Spam, Important, Newsletter, Personal.

Email:
"Subject: URGENT - You Won $1 Million! Click Now!
Dear Winner, Congratulations! You have been selected to receive $1 million. Click this link immediately to claim your prize: http://sketchy-site.com"

Provide:
1. Category
2. Confidence level (0-100%)
3. Reasoning (1 sentence)
"""



response = client.responses.create(
    model="gpt-5.2",
    input = prompt
)

response

Response(id='resp_0c4eb77b808662bb0069d46bf80ea481a08b46e08ecb96b0f2', created_at=1775528952.0, error=None, incomplete_details=None, instructions=None, metadata={}, model='gpt-5.2-2025-12-11', object='response', output=[ResponseOutputMessage(id='msg_0c4eb77b808662bb0069d46bf8e2f881a0988344a2ec4a83ea', content=[ResponseOutputText(annotations=[], text='1. **Category:** Spam  \n2. **Confidence level:** 99%  \n3. **Reasoning:** Uses urgent language, an unsolicited “you won” claim, and a suspicious link typical of phishing/scam emails.', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')], parallel_tool_calls=True, temperature=1.0, tool_choice='auto', tools=[], top_p=0.98, background=False, conversation=None, max_output_tokens=None, max_tool_calls=None, previous_response_id=None, prompt=None, prompt_cache_key=None, reasoning=Reasoning(effort='none', generate_summary=None, summary=None), safety_identifier=None, service_tier='default', status='completed', text=ResponseTextConfig(format=ResponseFormatText(type='text'), verbosity='medium'), top_logprobs=0, truncation='disabled', usage=ResponseUsage(input_tokens=105, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=50, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=155), user=None, billing={'payer': 'openai'}, completed_at=1775528953, frequency_penalty=0.0, presence_penalty=0.0, prompt_cache_retention=None, store=True)

In [5]:
response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

response.choices[0].message.content

'1. Category: Spam  \n2. Confidence level: 95%  \n3. Reasoning: The email contains a typical scam message promising a large monetary prize with a link to a suspicious website, which is characteristic of spam.'

In [ ]:

prompt = """You are an email classification system.
 Classify the following email into one of these categories: Spam, Important, Newsletter, Personal.

Email: {}
Provide:
1. Category
2. Confidence level (0-100%)
3. Reasoning (1 sentence)
"""

'You are an email classification system.\n Classify the following email into one of these categories: Spam, Important, Newsletter, Personal.\n\nEmail: testing my email\nProvide:\n1. Category\n2. Confidence level (0-100%)\n3. Reasoning (1 sentence)\n'

In [7]:
emails = [
    "Subject: URGENT - You Won $1 Million! Click Now! Dear Winner, Congratulations! You have been selected to receive $1 million. Click this link immediately to claim your prize: http://sketchy-site.com",
    "Subject: Meeting Reminder - Project Update Tomorrow at 10 AM. Hi Team, Just a reminder that we have our project update meeting scheduled for tomorrow at 10 AM in the conference room. Please come prepared with your progress reports and any blockers you are facing. Looking forward to seeing everyone there!",
    "Subject: Your Weekly Newsletter - Top Tech Trends This Week. Hello Subscriber, Welcome to your weekly dose of tech news! This week we cover the latest trends in AI, cybersecurity, and cloud computing. Stay informed and ahead of the curve with our expert analysis and insights.",
    "Subject: Family Reunion Plans - Save the Date! Dear Family, We are excited to announce that we are planning a family reunion for next summer! Please save the date for July 15th-17th. We will be sharing more details soon, but we wanted to make sure everyone has it on their calendar. Looking forward to seeing everyone!"
]

In [10]:
import pandas as pd
email_df = pd.DataFrame(emails, columns=["email"])
email_df.head()

                                               email
0  Subject: URGENT - You Won $1 Million! Click No...
1  Subject: Meeting Reminder - Project Update Tom...
2  Subject: Your Weekly Newsletter - Top Tech Tre...
3  Subject: Family Reunion Plans - Save the Date!...

In [17]:
def cleaning(output):
    cleaned = []
    for i in output.split("\n"):
        cleaned.append(i.strip())
    return cleaned

In [18]:
for i in range(len(emails)):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt.format(emails[i])}]
    )
    output = response.choices[0].message.content
    cleaned_output = cleaning(output)
    print(f"Email {i+1} Classification:\n{cleaned_output}\n")

Email 1 Classification:
['1. Category: Spam', '2. Confidence level: 95%', '3. Reasoning: The email contains a common spam characteristic of offering a large sum of money and includes a suspicious link, indicating it is likely designed to deceive recipients.']

Email 2 Classification:
['1. Category: Important', '2. Confidence level: 95%', '3. Reasoning: The email contains a reminder about a scheduled project update meeting, which is critical for team collaboration and progress tracking.']

Email 3 Classification:
['1. Category: Newsletter', '2. Confidence level: 95%', '3. Reasoning: The email is titled as a weekly newsletter and provides curated information on tech trends, indicating it is intended to inform subscribers rather than serve as a personal or promotional message.']

Email 4 Classification:
['1. Category: Personal', '2. Confidence level: 90%', '3. Reasoning: The email is addressed to family members and discusses a planned family event, indicating a personal connection.']

In [12]:
response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt.format(emails[0])}]
    )

output = response.choices[0].message.content

In [16]:
def cleaning(output):
    cleaned = []
    for i in output.split("\n"):
        cleaned.append(i.strip())
    return cleaned

cleaned_output = cleaning(output)
cleaned_output

['1. Category: Spam',
 '2. Confidence level: 95%',
 "3. Reasoning: The email contains a common spam motif of claiming large prizes requiring urgent action, along with a suspicious link, indicating it's likely to be a scam."]

In [ ]:
from langchain_openai import ChatOpenAI
model = ChatOpenAI(
    model="gpt-4o-mini"
)

AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 8, 'total_tokens': 17, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-mini-2024-07-18', 'system_fingerprint': 'fp_162d3c480f', 'finish_reason': 'stop', 'logprobs': None}, id='run--924dafb1-a3a9-4a43-826e-71f4a92b3090-0', usage_metadata={'input_tokens': 8, 'output_tokens': 9, 'total_tokens': 17, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [20]:
prompt = """You are an email classification system. Classify the following email into one of these categories: Spam, Important, Newsletter, Personal.

Email: {email} and Provide:
1. Overall Match Score (0-100)
2. Strengths (2-3 points)
3. Gaps/Concerns (2-3 points)
4. Final Recommendation: Strong Yes / Yes / Maybe / No
5. Brief reasoning (2 sentences)"""

model.invoke(prompt.format(email=emails[0])).content

'1. Overall Match Score: 95\n\n2. Strengths:\n   - The email uses urgent language that is typical of spam (e.g., "URGENT" and "You Won").\n   - The promise of a large monetary reward is a common tactic used in spam emails to attract attention.\n   - The presence of a suspicious link (http://sketchy-site.com) raises red flags regarding phishing attempts.\n\n3. Gaps/Concerns:\n   - The email lacks any personalization or specific details about the recipient.\n   - There is no legitimate source or company mentioned that could validate the claim.\n   - The language and formatting are typical of scams, which further diminishes credibility.\n\n4. Final Recommendation: Strong Yes\n\n5. Brief reasoning: The email exhibits all the characteristics of spam, including urgent claims, promises of large sums of money, and suspicious links. It is highly unlikely to be legitimate, and users should avoid engaging with it.'

In [22]:
from pydantic import BaseModel

class EmailClassification(BaseModel):
    email: str
    category: str
    overall_match_score: int
    strengths: list[str]
    gaps_concerns: list[str]
    final_recommendation: str
    brief_reasoning: str

In [23]:
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
parser = JsonOutputParser(pydantic_object=EmailClassification)


prompt = PromptTemplate(
     template= """You are an email classification system. 
    Classify the following email into one of these categories: Spam, Important, Newsletter, Personal.

    Email: {email}
    {format_instructions}

    """,
    input_variables=["email"],
    partial_variables={"format_instructions": parser.get_format_instructions()}
)

chain = prompt | model | parser

In [25]:
chain.invoke({"email": emails[0]})

{'email': 'Subject: URGENT - You Won $1 Million! Click Now! Dear Winner, Congratulations! You have been selected to receive $1 million. Click this link immediately to claim your prize: http://sketchy-site.com',
 'category': 'Spam',
 'overall_match_score': 95,
 'strengths': ['Contains keywords typically associated with scams',
  'Urgent call to action',
  'Promises a large monetary reward'],
 'gaps_concerns': ['Link provided appears suspicious',
  'No legitimate sender information',
  'Unrealistic offer'],
 'final_recommendation': 'Mark as Spam',
 'brief_reasoning': 'The email exhibits characteristics typical of spam and phishing attempts, including unrealistic promises and urgency.'}

In [29]:
for i in range(len(email_df)):
    raw_output = chain.invoke({"email": emails[i]})
    email_df.loc[i, "category"] = raw_output['category']
    email_df.loc[i, "overall_match_score"] = raw_output['overall_match_score']
    # email_df.loc[i, "strengths"] = raw_output['strengths']
    # email_df.loc[i, "gaps_concerns"] = raw_output['gaps_concerns']
    # email_df.loc[i, "final_recommendation"] = raw_output['final_recommendation']
    # email_df.loc[i, "brief_reasoning"] = raw_output['brief_reasoning']

In [30]:
email_df.head(2)

,email,category,overall_match_score,strengths,gaps_concerns
0,Subject: URGENT - You Won $1 Million! Click No...,Spam,95.0,nan,nan
1,Subject: Meeting Reminder - Project Update Tom...,Important,90.0,nan,nan

In [10]:
pip install langchain==0.3.11

Collecting langchain==0.3.11
  Using cached langchain-0.3.11-py3-none-any.whl.metadata (7.1 kB)
Collecting PyYAML>=5.3 (from langchain==0.3.11)
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting SQLAlchemy<3,>=1.4 (from langchain==0.3.11)
  Using cached sqlalchemy-2.0.48-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain==0.3.11)
  Downloading aiohttp-3.13.4-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting langchain-core<0.4.0,>=0.3.24 (from langchain==0.3.11)
  Using cached langchain_core-0.3.83-py3-none-any.whl.metadata (3.2 kB)
Collecting langchain-text-splitters<0.4.0,>=0.3.0 (from langchain==0.3.11)
  Using cached langchain_text_splitters-0.3.11-py3-none-any.whl.metadata (1.8 kB)
Collecting langsmith<0.3,>=0.1.17 (from langchain==0.3.11)
  Using cached langsmith-0.2.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy<3,>=1.26.2 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain==0.3.11) (2.4.3)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain==0.3.11) (2.12.5)
Collecting requests<3,>=2 (from langchain==0.3.11)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tenacity!=8.4.0,<10,>=8.1.0 (from langchain==0.3.11)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.11)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.11)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.11)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.11)
  Using cached frozenlist-1.8.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.11)
  Using cached multidict-6.7.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.11)
  Using cached propcache-0.4.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.11)
  Using cached yarl-1.23.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
INFO: pip is looking at multiple versions of langchain-core to determine which version is compatible with other requirements. This could take a while.
Collecting langchain-core<0.4.0,>=0.3.24 (from langchain==0.3.11)
  Using cached langchain_core-0.3.82-py3-none-any.whl.metadata (3.2 kB)
  Using cached langchain_core-0.3.81-py3-none-any.whl.metadata (3.2 kB)
  Using cached langchain_core-0.3.80-py3-none-any.whl.metadata (3.2 kB)
  Using cached langchain_core-0.3.79-py3-none-any.whl.metadata (3.2 kB)
  Using cached langchain_core-0.3.78-py3-none-any.whl.metadata (3.2 kB)
  Using cached langchain_core-0.3.77-py3-none-any.whl.metadata (3.2 kB)
  Using cached langchain_core-0.3.76-py3-none-any.whl.metadata (3.7 kB)
INFO: pip is still looking at multiple versions of langchain-core to determine which version is compatible with other requirements. This could take a while.
  Using cached langchain_core-0.3.75-py3-none-any.whl.metadata (5.7 kB)
  Using cached langchain_core-0.3.74-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.73-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.72-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.71-py3-none-any.whl.metadata (5.8 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached langchain_core-0.3.70-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.69-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.68-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.67-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.66-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.65-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.64-py3-none-any.whl.metadata (5.8 kB)
  Using cached langchain_core-0.3.63-py3-none-any.whl.metadata (5.8 kB)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core<0.4.0,>=0.3.24->langchain==0.3.11)
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting packaging<25,>=23.2 (from langchain-core<0.4.0,>=0.3.24->langchain==0.3.11)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: typing-extensions>=4.7 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.24->langchain==0.3.11) (4.15.0)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.24->langchain==0.3.11)
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting langchain-text-splitters<0.4.0,>=0.3.0 (from langchain==0.3.11)
  Using cached langchain_text_splitters-0.3.10-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langsmith<0.3,>=0.1.17->langchain==0.3.11) (0.28.1)
Collecting orjson<4.0.0,>=3.9.14 (from langsmith<0.3,>=0.1.17->langchain==0.3.11)
  Using cached orjson-3.11.7-cp313-cp313-macosx_15_0_arm64.whl.metadata (41 kB)
Collecting requests-toolbelt<2.0.0,>=1.0.0 (from langsmith<0.3,>=0.1.17->langchain==0.3.11)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: anyio in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.3,>=0.1.17->langchain==0.3.11) (4.13.0)
Requirement already satisfied: certifi in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.3,>=0.1.17->langchain==0.3.11) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.3,>=0.1.17->langchain==0.3.11) (1.0.9)
Requirement already satisfied: idna in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.3,>=0.1.17->langchain==0.3.11) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.3,>=0.1.17->langchain==0.3.11) (0.16.0)
Requirement already satisfied: pip>=25.2 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-text-splitters<0.4.0,>=0.3.0->langchain==0.3.11) (25.3)
Collecting langchain-text-splitters<0.4.0,>=0.3.0 (from langchain==0.3.11)
  Using cached langchain_text_splitters-0.3.9-py3-none-any.whl.metadata (1.9 kB)
  Using cached langchain_text_splitters-0.3.8-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain==0.3.11) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain==0.3.11) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain==0.3.11) (0.4.2)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2->langchain==0.3.11)
  Using cached charset_normalizer-3.4.6-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2->langchain==0.3.11)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Using cached langchain-0.3.11-py3-none-any.whl (1.0 MB)
Downloading aiohttp-3.13.4-cp313-cp313-macosx_11_0_arm64.whl (498 kB)
Using cached langchain_core-0.3.63-py3-none-any.whl (438 kB)
Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Using cached langsmith-0.2.11-py3-none-any.whl (326 kB)
Using cached langchain_text_splitters-0.3.8-py3-none-any.whl (32 kB)
Using cached multidict-6.7.1-cp313-cp313-macosx_11_0_arm64.whl (43 kB)
Using cached orjson-3.11.7-cp313-cp313-macosx_15_0_arm64.whl (125 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.6-cp313-cp313-macosx_10_13_universal2.whl (294 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached sqlalchemy-2.0.48-cp313-cp313-macosx_11_0_arm64.whl (2.2 MB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached yarl-1.23.0-cp313-cp313-macosx_11_0_arm64.whl (85 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached frozenlist-1.8.0-cp313-cp313-macosx_11_0_arm64.whl (49 kB)
Using cached jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Using cached propcache-0.4.1-cp313-cp313-macosx_11_0_arm64.whl (46 kB)
Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Installing collected packages: urllib3, tenacity, SQLAlchemy, PyYAML, propcache, packaging, orjson, multidict, jsonpointer, frozenlist, charset_normalizer, attrs, aiohappyeyeballs, yarl, requests, jsonpatch, aiosignal, requests-toolbelt, aiohttp, langsmith, langchain-core, langchain-text-splitters, langchain
  Attempting uninstall: packaging━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/23 [SQLAlchemy]
    Found existing installation: packaging 26.0━━━━━━━━━━━━━━━  2/23 [SQLAlchemy]
    Uninstalling packaging-26.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/23 [SQLAlchemy]
      Successfully uninstalled packaging-26.0━━━━━━━━━━━━━━━━━  2/23 [SQLAlchemy]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23/23 [langchain]23 [langchain]core]zer]
Successfully installed PyYAML-6.0.3 SQLAlchemy-2.0.48 aiohappyeyeballs-2.6.1 aiohttp-3.13.4 aiosignal-1.4.0 attrs-26.1.0 charset_normalizer-3.4.6 frozenlist-1.8.0 jsonpatch-1.33 jsonpointer-3.1.1 langchain-0.3.11 langchain-core-0.3.63 langchain-text-splitters-0.3.8 langsmith-0.2.11 multidict-6.7.1 orjson-3.11.7 packaging-24.2 propcache-0.4.1 requests-2.33.1 requests-toolbelt-1.0.0 tenacity-9.1.4 urllib3-2.6.3 yarl-1.23.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [11]:
pip install langchain-openai==0.2.12

Collecting langchain-openai==0.2.12
  Using cached langchain_openai-0.2.12-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: langchain-core<0.4.0,>=0.3.21 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-openai==0.2.12) (0.3.63)
Collecting openai<2.0.0,>=1.55.3 (from langchain-openai==0.2.12)
  Using cached openai-1.109.1-py3-none-any.whl.metadata (29 kB)
Collecting tiktoken<1,>=0.7 (from langchain-openai==0.2.12)
  Using cached tiktoken-0.12.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.7 kB)
Requirement already satisfied: langsmith<0.4,>=0.1.126 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (0.2.11)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (9.1.4)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (1.33)
Requirement already satisfied: PyYAML>=5.3 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (6.0.3)
Requirement already satisfied: packaging<25,>=23.2 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (24.2)
Requirement already satisfied: typing-extensions>=4.7 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (4.15.0)
Requirement already satisfied: pydantic>=2.7.4 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (2.12.5)
Requirement already satisfied: jsonpointer>=1.9 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (3.1.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (3.11.7)
Requirement already satisfied: requests<3,>=2 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (2.33.1)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (1.0.0)
Requirement already satisfied: anyio in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (4.13.0)
Requirement already satisfied: certifi in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (1.0.9)
Requirement already satisfied: idna in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (0.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from openai<2.0.0,>=1.55.3->langchain-openai==0.2.12) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from openai<2.0.0,>=1.55.3->langchain-openai==0.2.12) (0.13.0)
Requirement already satisfied: sniffio in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from openai<2.0.0,>=1.55.3->langchain-openai==0.2.12) (1.3.1)
Requirement already satisfied: tqdm>4 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from openai<2.0.0,>=1.55.3->langchain-openai==0.2.12) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from pydantic>=2.7.4->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from pydantic>=2.7.4->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from pydantic>=2.7.4->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from requests<3,>=2->langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/rahultiwari/Documents/02_Freelancing/Hachion_batch/agent-ai-training/ai-env/lib/python3.13/site-packages (from requests<3,>=2->langsmith<0.4,>=0.1.126->langchain-core<0.4.0,>=0.3.21->langchain-openai==0.2.12) (2.6.3)
Collecting regex>=2022.1.18 (from tiktoken<1,>=0.7->langchain-openai==0.2.12)
  Downloading regex-2026.3.32-cp313-cp313-macosx_11_0_arm64.whl.metadata (40 kB)
Using cached langchain_openai-0.2.12-py3-none-any.whl (50 kB)
Using cached openai-1.109.1-py3-none-any.whl (948 kB)
Using cached tiktoken-0.12.0-cp313-cp313-macosx_11_0_arm64.whl (993 kB)
Downloading regex-2026.3.32-cp313-cp313-macosx_11_0_arm64.whl (289 kB)
Installing collected packages: regex, tiktoken, openai, langchain-openai
  Attempting uninstall: openai
    Found existing installation: openai 2.30.0
    Uninstalling openai-2.30.0:
      Successfully uninstalled openai-2.30.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [langchain-openai][openai]
Successfully installed langchain-openai-0.2.12 openai-1.109.1 regex-2026.3.32 tiktoken-0.12.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate

prompt_txt = '{query}'
prompt = ChatPromptTemplate.from_template(prompt_txt)
model = ChatOpenAI(model="gpt-5.2")

OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

In [15]:
from langchain.chains import LLMChain

llm_model = LLMChain(llm=model,prompt=prompt)

/var/folders/fq/kr6gv5l17pd4j572n0_n3f2c0000gn/T/ipykernel_9154/4077653310.py:3: LangChainDeprecationWarning: The class `LLMChain` was deprecated in LangChain 0.1.17 and will be removed in 1.0. Use :meth:`~RunnableSequence, e.g., `prompt | llm`` instead.
  llm_model = LLMChain(llm=model,prompt=prompt)

In [19]:
reponse = llm_model.invoke({"query":"Can you teach me how to do scam"})

In [21]:
reponse['text']

'I can’t help with scams or anything meant to deceive or steal from people.\n\nIf you tell me what you’re trying to achieve (e.g., make money online, market a product, negotiate, spot scams, or recover from being scammed), I can help with a legitimate alternative. Here are a few options:\n\n- **Learn to spot and avoid scams:** common tactics, red flags, and how to verify legitimacy.  \n- **Make money ethically online:** freelancing, tutoring, selling digital products, affiliate marketing (properly disclosed), or starting a small service business.  \n- **Cybersecurity/anti-fraud skills:** how scammers operate at a high level, and how to protect yourself or your organization.  \n- **If you’ve been scammed:** steps to secure accounts, document evidence, and report it.\n\nWhich of these best matches what you need?'