In [1]:
import pandas as pd

data = pd.read_csv("simple_data.csv")

In [2]:
type(data)

pandas.DataFrame

In [3]:
data.head() # select *n from data

  product_category   price  rating
0             Book   12.99     4.5
1             Book   15.49     4.0
2      Electronics  199.99     3.5
3         Clothing   29.99     5.0
4      Electronics   99.99     4.2

In [4]:
data['price'] # select price from data
type(data['price'] )
data['price'] # select avg(price) from data

0     12.99
1     15.49
2    199.99
3     29.99
4     99.99
Name: price, dtype: float64

In [5]:
data[['price','rating']].describe()

          price    rating
count    5.0000  5.000000
mean    71.6900  4.240000
std     80.0075  0.559464
min     12.9900  3.500000
25%     15.4900  4.000000
50%     29.9900  4.200000
75%     99.9900  4.500000
max    199.9900  5.000000

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_category  5 non-null      str
 1   price             5 non-null      float64
 2   rating            5 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

In [7]:
import numpy as np
data = {
    'orderId':[1,2,3,4,5],
    'delivery_time':[30,45,20,35,50],
    'customer_feedback':[np.nan,4.5,3.0,4.0,np.nan]
}

df = pd.DataFrame(data)
df.head(2)

   orderId  delivery_time  customer_feedback
0        1             30                NaN
1        2             45                4.5

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   orderId            5 non-null      int64
 1   delivery_time      5 non-null      int64
 2   customer_feedback  3 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 252.0 bytes

In [9]:
df.isnull().sum()

orderId              0
delivery_time        0
customer_feedback    2
dtype: int64

In [15]:
import numpy as np
data = {
    'age': np.random.randint(0, 100, 500),
    'income': np.random.randint(20000, 100000, 500),
    'city': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], 500)
}


customer_data = pd.DataFrame(data)
customer_data.head()

   age  income         city
0   45   43147      Houston
1   88   29112  Los Angeles
2   57   90409      Phoenix
3   59   66813     New York
4   10   76897     New York

In [17]:
customer_data.city.value_counts()

city
Chicago        113
Houston        107
Phoenix         97
Los Angeles     94
New York        89
Name: count, dtype: int64

In [16]:
customer_data.shape

(500, 3)

In [23]:
customer_data.groupby('city')['income'].max()

city
Chicago        98211
Houston        99667
Los Angeles    99610
New York       99233
Phoenix        99424
Name: income, dtype: int64

In [24]:
customer_data.groupby('city').agg({
    'income': ['max', 'min', 'mean']
})

            income
               max    min          mean
city
Chicago      98211  20500  59805.336283
Houston      99667  21144  58291.383178
Los Angeles  99610  20498  56286.755319
New York     99233  20020  56923.685393
Phoenix      99424  20481  59025.680412

In [21]:
data = {
    'age': np.random.randint(0, 100, 500),
    'income': np.random.randint(20000, 100000, 500),
    'price': np.random.randint(5, 500, 500),
    'city': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], 500),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Groceries', 'Books', 'Furniture'], 500)
}


sales_df = pd.DataFrame(data)

sales_df.head(2)

   age  income  price         city product_category
0   17   60074     72      Phoenix      Electronics
1   60   57967    312  Los Angeles        Groceries

In [25]:
sales_df.groupby('city').agg({
    'income': ['max', 'min', 'mean'],
    'price': ['max', 'min', 'mean']
})

            income                      price
               max    min          mean   max min        mean
city
Chicago      99762  20049  59115.462963   494  21  259.203704
Houston      99884  21166  63462.635294   498  11  280.529412
Los Angeles  99622  20573  62052.204301   491   9  239.397849
New York     99801  21044  56132.320388   498  15  272.446602
Phoenix      99005  21571  60347.018018   497  10  260.675676

In [28]:
sales_df.groupby(['city', 'product_category']).agg({
    'price': ['max', 'min', 'mean','std']
})

                             price
                               max  min        mean         std
city        product_category
Chicago     Books              363   21  191.153846  111.794340
            Clothing           479   50  266.551724  130.078160
            Electronics        494   54  246.058824  135.778989
            Furniture          474   57  292.739130  124.540690
            Groceries          494   60  263.961538  134.875789
Houston     Books              496   42  284.666667  137.843510
            Clothing           498   37  308.450000  138.013148
            Electronics        498   35  259.000000  154.042202
            Furniture          497   11  266.307692  159.467544
            Groceries          467   95  271.937500  103.813595
Los Angeles Books              489   20  257.789474  154.578847
            Clothing           491    9  219.294118  143.392279
            Electronics        484   28  239.454545  119.661319
            Furniture          491   18  268.611111  144.869978
            Groceries          416   16  207.941176  129.336997
New York    Books              458   15  301.235294  124.850175
            Clothing           480   20  241.764706  132.258048
            Electronics        442   32  257.576923  122.292493
            Furniture          498   74  243.833333  141.990100
            Groceries          482  123  330.631579  101.354828
Phoenix     Books              481   10  202.375000  146.785955
            Clothing           495   40  291.615385  127.918748
            Electronics        477   58  248.263158  136.053846
            Furniture          465   21  263.862069  127.666900
            Groceries          497   10  273.619048  144.145231

In [30]:
# in groupby : agg function : you can also pass 
def range_func(x):
    return x.max() - x.min()

result_df = sales_df.groupby(['city', 'product_category']).agg({
    'price': ['max', 'min', 'mean', range_func]
})

# order by
result_df = result_df.sort_values(by=('price', 'mean'), ascending=False)
result_df.head(10)

                             price
                               max  min        mean range_func
city        product_category
New York    Groceries          482  123  330.631579        359
Houston     Clothing           498   37  308.450000        461
New York    Books              458   15  301.235294        443
Chicago     Furniture          474   57  292.739130        417
Phoenix     Clothing           495   40  291.615385        455
Houston     Books              496   42  284.666667        454
Phoenix     Groceries          497   10  273.619048        487
Houston     Groceries          467   95  271.937500        372
Los Angeles Furniture          491   18  268.611111        473
Chicago     Clothing           479   50  266.551724        429

In [31]:
result_df.to_csv('sales_analysis.csv')

In [32]:
result_df.to_html('sales_analysis.html')

In [33]:
type(result_df)

pandas.DataFrame

In [43]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[5, 6, 7, 8],
)

final_df = pd.concat([df1, df2],axis=1) #if axis=0 = row-wise concatenation else column-wise
final_df

     A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   A4   B4   C4   D4
6  NaN  NaN  NaN  NaN   A5   B5   C5   D5
7  NaN  NaN  NaN  NaN   A6   B6   C6   D6
8  NaN  NaN  NaN  NaN   A7   B7   C7   D7